name: Chaining Job

on:
  workflow_dispatch:
    inputs:
        Run-Job-3:
            type: boolean
            default: false
            description: "Whether to run Job 3 or not"

jobs:
    Job1:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: echo "This is Job 1, Run Job 3 input is ${{ github.event.inputs.Run-Job-3 }}"

    Job2:
        runs-on: ubuntu-latest
        needs: Job1
        steps:  
            - name: Step 1
              run: echo "This is Job 2"
            - name: Step 2
              run: exit 1
    
    Job3:
        runs-on: ubuntu-latest
        if : github.event.inputs.Run-Job-3 == 'true'
        needs: 
            - Job1
        steps:
            - name: Step 1
              run: echo "This is Job 3, which runs only if the input is true"

    Job4:
        runs-on: ubuntu-latest
        needs: 
            - Job2
            - Job3
        # if: always()
        steps:
            - name: Step 1
              run: echo "This is Job 4, which runs after Job 2 and Job 3 (if Job 3 was triggered)"