name: "Terraform Apply"

on:
  push:
    branches: [ master ]
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      TF_VAR_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      TF_VAR_CHAT_ID: ${{ secrets.CHAT_ID }}
      TF_VAR_ECS_SECURITY_GROUP: ${{ secrets.ECS_SECURITY_GROUP }}
      TF_VAR_ECS_SUBNET_ID: ${{ secrets.ECS_SUBNET_ID }}
      TF_VAR_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    defaults:
      run:
        working-directory: ./infra/live/app_services
    
    steps:    
      - name: Inform on PR that Apply is Running
        uses: mshick/add-pr-comment@v1
        with:
            repo-token: ${{ secrets.CUSTOM_PAT }}
            repo-token-user-login: 'github-actions[bot]'
            message: |
                ***Running terraform apply***
                Results will display here momentarily...

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::916194680580:role/Zeteon_GitHub_Actions_Role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init
    
      - name: Teeraform Plan
        id: plan
        run: terraform plan -input=false -no-color -out=tfplan && terraform show -no-color tfplan

      - name: Reformat Plan
        if: steps.plan.outcome == 'success'
        run: |
            echo '${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}' \
            | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > plan.txt          
    
      - name: Put Plan in Env Var
        if: steps.plan.outcome == 'success'
        run: |
            PLAN=$(cat plan.txt)
            echo "PLAN<<EOF" >> $GITHUB_ENV
            echo "$PLAN" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV 

      - name: Terraform Apply
        id: apply
        continue-on-error: true
        if: steps.plan.outcome == 'success'
        run: terraform apply -auto-approve -input=false

      - name: Post Plan and Apply to GitHub PR
        if: steps.plan.outcome == 'success' && steps.apply.outcome == 'success'
        uses: mshick/add-pr-comment@v1
        with:
            repo-token: ${{ secrets.CUSTOM_PAT }}
            repo-token-user-login: 'github-actions[bot]'
            message: |
                ***Applying **Infra**:
                <details><summary>Show Apply</summary>
                ```
                ${{ steps.apply.outputs.stdout }}
                ```
                </details>
    
      - name: Post Plan Failure
        if: steps.plan.outcome == 'failure'
        uses: mshick/add-pr-comment@v1
        with:
            repo-token: ${{ secrets.CUSTOM_PAT }}
            repo-token-user-login: 'github-actions[bot]'
            message: |
                ***Plan failed for **Infra**:
                <details><summary>Show Plan Fail</summary>
                ```
                ${{ steps.plan.outputs.stderr }}
                ```
                </details>

      - name: Post Apply Failure
        if: steps.apply.outcome == 'failure'
        uses: mshick/add-pr-comment@v1
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            repo-token-user-login: 'github-actions[bot]'
            message: |
                ***Apply failed for **Infra**:
                <details><summary>Show Apply Fail</summary>
                ```
                ${{ steps.apply.outputs.stderr }}
                ```
                </details>