name : "Github Action Tutorial"

on:
    workflow_dispatch:
        inputs:
            name:
                description: "Person to greet"
                default : "World"
                required: true
                type: string
            
            city:
                description: "City they live"
                default: "London"
                required: true
                type: choice
                options:
                    - New York
                    - London
                    - Paris

jobs:
    greet:
        name: "Greeting, Program!"
        runs-on:
            - ubuntu-latest
        steps:
            - name: Send greeting
              run: |
                echo "Hello ${{ github.event.inputs.name }}"
                echo "You live in ${{ github.event.inputs.city}}"



